### ISSUE TITLE
Quran Ayahs

### ISSUE THREAD

**Issue by FarisFarley** [mosamabinomar/quranVerses#1]
Assalamo Alaikum. Brother hopefully you are doing good In Sha Allah, brother I want to show the hadith and quranic ayahs in the google card view and want to change the fonts of the text. how is that possible? hadith and its references are combined.. i want to show them in a seperate text in the card. please advise me how to do that or the options are limited  ?

**Comment by bullheadandplato** [comment]
Wa-alikum-aslam, To get Quran ayah you can use `QuranQuote.getInstance(context).getRandomVerse()`
To get Hadith you can use `HadithQuote.getInstance(context).getRandomHadith()`

**Comment by FarisFarley** [comment]
> Wa-alikum-aslam, To get Quran ayah you can use `QuranQuote.getInstance(context).getRandomVerse()`
> To get Hadith you can use `HadithQuote.getInstance(context).getRandomHadith()`

Sorry i dint get that... for example if i want to get two seperate text view (the ayah) ( reference)  in two different text and display it in cardview hows that possible  ? please kindly show with example e.g  textview = findviewbyid(R.id. ayah)
       textview = findviewbyid(R.id. reference)

now how to get them in each textview and the reference ?

**Comment by bullheadandplato** [comment]
When you will call `QuranQuote.getInstance(context).getRandomVerse()` it will return object of [Verse](https://github.com/bullheadandplato/quranVerses/blob/master/quranquotes/src/main/java/com/bullhead/quranquotes/domain/Verse.java) it will have all the required properties like ayah text reference etc
