### ISSUE TITLE
Failed to resolve: com.github.mosamabinomar:quranVerses:2.0

### ISSUE THREAD

**Issue by illahi-production** [mosamabinomar/quranVerses#2]
Failed to resolve: com.github.mosamabinomar:quranVerses:2.0

compileSdk 32
minSdk 19
targetSdk 31

**Comment by bullheadandplato** [comment]
`implementation 'com.github.bullheadandplato:quranVerses:2.0'`

**Comment by illahi-production** [comment]
Unresolved dependencies

Could not resolve com.github.bullheadandplato:quranVerses:2.0

not solving problem

**Comment by bullheadandplato** [comment]
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
Did you add` jitpack.io` in your repositories like above?
